.github/workflows/ci.yaml, .github/workflows/release.yaml
We run the integration tests upon push to `main` through the `release` workflows. We duplicate these tests by running the `ci` workflows as well.
Disable running tests upon push to `main`.
Run the CI integration tests upon pull request only
=> Run the CI integration tests upon pull request only

.github/workflows/ci.yaml, .github/workflows/release.yaml
1. We are running heavy integration tests even if the lighter ones (like linting and unit tests) 
2. We are repeating CI workflows in ci.yaml and release.yaml
1. Introduce dependencies to only run the heavier CI workflows after the lighter ones finish successfully
2. Import CI workflows from ci.yaml into release.yaml
Add CI workflow dependency + import integration test CI workflows
=> Add CI workflow dependency + import integration test CI workflows

.github/workflows/release.yaml
We're running into the [following error](https://github.com/canonical/mysql-router-k8s-operator/actions/runs/3206628347/jobs/5241167958#step:4:15) when trying to release the charm to charmhub using CI. We speculate that since the version of the charming actions is old, it is retrieving the tag version as `undefined` and trying to tag the repo with `revundefined` (which already exists).
Update the version of the `channel` and `upload-charm` actions to `2.0.0-rc`
Bump the charming actions version for releasing the charm
=> Bump the charming actions version for releasing the charm

tests/unit/__init__.py
It is a side effect fix in DPE-904 to address annoying warning.
Use SIMULATE_CAN_CONNECT=True as recommended by Juju SDK.
Just a warning fix, should have no other effect.
Juju testing SDK: use SIMULATE_CAN_CONNECT=True for better connection tracking.
Just a warning fix, should have no other effect.
=> DPE-904 Fixing Juju SDK warning: SIMULATE_CAN_CONNECT=True

.github/workflows/ci.yaml, .github/workflows/release.yaml, charmcraft.yaml
Release to charmhub action is [failing](https://github.com/canonical/mysql-k8s-operator/actions/runs/3256480064/jobs/5347273232#step:4:63) due to a change in the way resources are uploaded to charmhub.
Upgrade the charming action to v2.1.1 which should resolve the issue
Upgrade charming actions to v2.1.1 to resolve upload to charmhub issue
=> Upgrade libraries and environment versions to fix building/releasing.

src/charm.py, src/relations/database_provides.py, src/relations/database_requires.py, tests/unit/test_charm.py
[DPE-1114](https://warthogs.atlassian.net/browse/DPE-1114)
[Issue 11](https://github.com/canonical/mysql-router-k8s-operator/issues/11) and [Issue 12](https://github.com/canonical/mysql-router-k8s-operator/issues/12)
1. When new mysql-router-k8s units are added, they do not go active until the next update-status hook runs (they are not bootstrapped until the next update-status hook)
2. We are blanket setting the unit status as `WaitingStatus` on leader-elected. Thus, if the application leader changes, the status is set to `waiting` even if it is supposed to be `active`
1. When we form a relation with the consumer application, we are setting some information in the peer relation (this is exactly when the unit has all the information to be bootstrapped). Thus, bootstrap the unit upon …
=> Bootstrap new units as soon as possible instead of doing so in update-status

.github/workflows/ci.yaml, tests/integration/test_charm.py
The test was failing to bootstrap mysql-k8s charm due to the recent changes there in commit a6f1f01: Fix/endpoints as k8s services (#142).
Also 'Dump logs' GitHub CI step was failing due to wrong app name used, fixed names to match official charm names (for simplicity).
Add missing flag `--trust` to bootstrap `mysql-k8s` and rename apps to match official naming.
=> Fix failing integration-database CI test

.github/workflows/release.yaml
It is not possible to build focal charms on jammy GH runner:
> /usr/bin/sudo charmcraft pack --destructive-mode --quiet
> No suitable 'build-on' environment found in any 'bases' configuration.
> Full execution log: '/root/.local/state/charmcraft/log/charmcraft-20230227-190524.251127.log'
Disable ` --destructive-mode -` so `charmcraft pack` will use lxc container to build a charm.
=> Disabling destructive-mode for upload-charm action and update versions

metadata.yaml
The interface name is using `-`, but naming convention says `_`.
https://juju.is/docs/sdk/styleguide
The endpoint name should use `-`, but interface name `_`.
=> Update peer interface names to follow naming conventions

.github/workflows/ci.yaml, charmcraft.yaml, requirements.txt, tests/unit/__init__.py, tox.ini
We were using an old juju-agent due to several open issues in 2.9.30+, but none are affecting tests in this repo.
Updating juju-agent to the latest 2.9.42.
Also removing no longer necessary pinning for flake8, bumping ops pinning and removing not necessary SIMULATE_CAN_CONNECT (it is enabled by default for ops 2.0+).
=> Bump juju-agent to 2.9.42, unpin flake8 and remove unnecessary SIMULATE_CAN_CONNECT

metadata.yaml
* documentation on Discourse was missing
* metadata.yaml was outdated (missing lings, outdated year, wrong summary, etc)
We are preparing the charm for release to stable and need to
generate all the necessary documentation/links on https://charmhub.io/mysql-router-k8s
* update metadata.yaml to match mysql-k8s concepts
* add Discourse documentation Overview page
=> DPE-2752 Add Discourse documentation + update metadata.yaml

lib/charms/data_platform_libs/v0/data_interfaces.py
Upgrading library dependency `data_platform_libs/data_interfaces` to latest version v24.
Fixing issues:
- https://github.com/canonical/data-platform-libs/issues/111
- https://github.com/canonical/data-platform-libs/issues/108
=> [DPE-3022] data_platform_libs/data_interfaces v24

templates/logrotate.j2
We are using `-%V_%H%M` as the dateformat for logrotate - this causes filename conflicts after a day of uptime due to file name conflicts.
Use `-%Y%m%d_%H:%M` as the dateformat (for consistency with pgbouncer)
=> [DPE-3063] Update logrotate dateformat to tolerate more than 24hrs of uptime

src/abstract_charm.py, src/kubernetes_charm.py, src/relations/database_provides.py, src/relations/tls.py, src/workload.py, tests/integration/connector.py, tests/integration/helpers.py, tests/integration/juju_.py, tests/integration/markers.py, tests/integration/test_node_port.py, tests/unit/conftest.py
DPE-3771: In case mysql-router is connected with any app that sets `external-node-connectivity=true`, then NodePort must be configured and shared via relation. Applications that do not set it will receive the internal k8s DNS record instead. This way, an application, if running within the same k8s cluster, can choose to go through the internal cluster IPs and reduce its own latency.
An app outside of Juju ecosystem can connect with the database by relating the router with data-integrator, which triggers the creation of the NodePort. Then, the NodePort can be used to connect.
TLS is managed as well, in this change. If TLS and NodePort are both enabled, then the workers' IPs and hostnames where the routers are placed are captured and added as SANs to the certificate.
=> [DPE-3771] Add node port support

.github/workflows/release.yaml
As part of [PR 237](https://github.com/canonical/mysql-router-k8s-operator/pull/237), the `lib-check` CI step was moved to run during pull request from release. However, the release still `needs` `lib-check` which no longer exists
Remove the `lib-check` pre-req for release
=> Remove lib-check prereq for running release

poetry.lock, pyproject.toml, tox.ini
1. We are not defining a lower bound for the `ops` package
2. We are not generating a coverage report for unit tests
1. Set `2.6.0` as the lower bound
2. Add option to generate coverage
=> Add option for unit test coverage

.github/workflows/sync_docs.yaml
Problem:
The stable branch is diverged from main the last half a year and some fixes on main looks like the problem we see in CI.
Solution:
Try to use `main`.
=> Update gatekeeper revision

.github/workflows/sync_docs.yaml
We are continue testing the gatekeeper to re-enable the documentation sync.
=> Reverting gatekeeper to main

metadata.yaml, src/relations/cos.py, src/rock.py, tests/integration/test_exporter.py, tests/integration/test_exporter_with_tls.py
We are finding connections in `TIME_WAIT` between router exporter and mysql (still investigating what is happening here). Due to pebble's `on-failure: restart`, the exporter service eventually is able to start up when the connection in `TIME_WAIT` terminates after 60s - however, our retry in the test is 3 mins sometimes does not provide enough time for pebble's exponential backoff to work 
Extend the timeout to 7 mins
=> [DPE-4173] Stabilize exporter tests by using listen-port to avoid ephemeral ports

charmcraft.yaml, lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/loki_k8s/v1/loki_push_api.py, lib/charms/tempo_k8s/v1/charm_tracing.py, lib/charms/tempo_k8s/v2/tracing.py, lib/charms/tls_certificates_interface/v2/tls_certificates.py, poetry.lock, src/relations/tls.py, tests/integration/test_upgrade.py
1. We use time.sleep instead of a deterministic way to determine when to send `resume-upgrade` after rolling back. This sometimes leads to [this error](https://github.com/canonical/mysql-router-k8s-operator/actions/runs/10312040824/job/28546894902#step:31:2522) when `resume-upgrade` is run too early
```
Resume upgrade event failed: Highest number unit is unhealthy. Upgrade will not resume.
```
2. We are using `prime` in charmcraft which is deprecated in charmcraft 3.1.1
1. Use a more deterministic approach - check that all units are `active` and `idle` (one will have rolled back while the other two will not)
2. Use parts to prime version files and the dump plugin to prime scripts/ directory
=> [DPE-4739] Avoid using time.sleep in rollback integration tests

.github/workflows/sync_docs.yaml
This PR changes the `sync_docs.yaml` workflow to the [new version with a different backend](https://github.com/canonical/data-platform-workflows/pull/220#issue-2449415094).
=> Update sync_docs.yaml 

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/loki_k8s/v1/loki_push_api.py, lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py, lib/charms/tempo_coordinator_k8s/v0/tracing.py, pyproject.toml, src/abstract_charm.py, src/kubernetes_charm.py, tests/unit/conftest.py
There are a bunch of tempo tracing related updates:
1. tempo-k8s has been deprecated in favor of tempo ha
2. tracing charm libs need to be fetch-ed from tempo_coordinator_k8s
3. tracing traffic is now relayed through grafana-agent-k8s (like the remaining COS traffic)
2. update tracing charm libs from new repo
Test integration with tempo ha + test relay of traffic through grafana-agent-k8s
Update mysql-router-k8s tracing related documentation (in progress)
=> [DPE-5312] Update tracing charm libs to retrieve them from tempo coordinator repo

src/kubernetes_upgrade.py, src/workload.py
This PR adds warning level messages when a _destructive_ action is performed. The definition of _destructive_ seems to be associated with data loss, which I think it can only happen, from user action, whenever they force a primary failover without checking considering the health of such instance.
- Paulo confirmed that this ticket was created to familiarised myself with the codebases.
- Alex referenced this PostgreSQL operator [PR](https://github.com/canonical/postgresql-k8s-operator/pull/753) as the reason behind the need for warnings.
=> [DPE-5711] Add warnings to destructive actions

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/sync_docs.yaml, src/abstract_charm.py, src/kubernetes_charm.py
While standardizing code in the router vm charm (https://github.com/canonical/mysql-router-operator/pull/182), there were small minor adjustments that needed to be made in the code in this repo
Propagate appropriate changes
=> Minor adjustments while standarding shared code with the router vm charm

.github/workflows/charm_libs.yaml, .github/workflows/ci.yaml
This PR moves the charm libs check to its own workflow, signalling outdated charm libs with a label, instead of making CI fail (Similar to what PostgreSQL repositories do).
=> [DPE-6653] Signal outdated charm libs with a label

src/container.py, src/mysql_shell/__init__.py, src/mysql_shell/templates/try_except_wrapper.py.jinja
We are storing passwords on disk (in the mysqlsh python script) when we execute mysqlsh. This is a security vulnerability
Avoid writing passwords on disk, and instead use --passwords-from-stdin flag of mysqlsh
=> [DPE-6447] Avoid storing passwords on disk when running mysqlsh

tests/integration/test_expose_external.py
This PR bumps the charm base for the `data-integrator` charm, which was updated on [this PR](https://github.com/canonical/data-integrator/pull/132) back in April 9th.
=> [MISC] Update data-integrator charm base
